// Auto-generated by storybook-visual-regression
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  retries: 2,
  workers: 4,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:6006/:6006',
    headless: true,
    timezoneId: 'Europe/London',
    locale: 'en-GB',
  },
  webServer: {
    command: 'npm',
    args: ['run', 'storybook'],
    url: 'http://localhost:6006/:6006',
    reuseExistingServer: true,
    timeout: 60000,
  },
});
